apiVersion: v1
kind: Service
metadata:
  name: my-web-service
spec:
  type: NodePort
  selector:
    app: my-web
  ports:
    - port: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
spec:
  selector:
    matchLabels:
      run: my-web
  replicas: 2
  template:
    metadata:
      labels:
        app: my-web
        run: my-web
    spec:
      containers:
      - name: my-web
        image: adeharrison/springbootrestapiexample2
        ports:
        - containerPort: 8081
